name: Build Doom Emacs

on:
  schedule:
    # At 12pm UTC (SG time 8pm) past every 24th hour.
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  build-all:
    runs-on: macos-latest
    steps:
      # setup nix and cachix environment
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: emacs-osx
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Install emacs with native-compilation
        run: |
          REL=https://github.com/sagittaros/emacs-osx/archive/refs/tags/built.tar.gz
          nix-env -iA emacsOsxNative -f $REL

      - name: Build doom emacs
        run: |
          git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
          ~/.emacs.d/bin/doom install --yes

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Gzip .emacs.d if build was successful
        if: ${{ success() }}
        run: |
          tar -czvf dot-emacs-d-native.tar.gz ~/.emacs.d
          git commit -m "Updated doom build"
          git push
