name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Update Emacs Source"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-workflow-configuration
  workflow_dispatch:

jobs:
  emacsOsx:
    runs-on: macos-latest
    steps:
      # setup nix and cachix environment
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: emacs-osx
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          
      # now the actual build
      - run: nix-build -A emacsOsx

  emacsOsxPlus:
    runs-on: macos-latest
    steps:
      # setup nix and cachix environment
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: emacs-osx
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          
      # now the actual build
      - run: nix-build -A emacsOsxPlus